// <auto-generated />
namespace SittingPlan.Data.Migrations.MyHistory
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class personChairRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(personChairRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201909021015419_personChairRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
